/**
 * Keep the receipts OUT of Android's Auto Backup.
 *
 * Auto Backup gives every app a private folder in the user's Google Drive:
 * free, nightly, doesn't count against their storage, and restored
 * automatically onto a new phone. It is the best backup we get for no code
 * at all — and it has a hard ceiling of 25 MB per app.
 *
 * The failure past that ceiling is the nasty part. Android does not back up
 * "as much as fits". It calls onQuotaExceeded() and backs up NOTHING — not the
 * photos, not the database, not the settings. Silently. No error the user ever
 * sees. So an app that lets receipt photos into that 25 MB is an app that
 * quietly stops backing up somewhere around the hundredth receipt, and the
 * person only discovers it on the day they lose their phone.
 *
 * A shrunk receipt is 150-250 KB. The database, even after years of daily use,
 * is a couple of megabytes. So the rule writes itself: the database goes to
 * Drive and the photos do not. The photos have their own route out — the ZIP
 * in the folder you choose, and the copy in Drive if you connect it.
 *
 * `backups/` is excluded for the same reason and one more: a snapshot of the
 * database, sitting inside the cloud backup of that same database, protects
 * against nothing and costs the quota that the database needs.
 *
 * Two files because Android changed the format in 12 and the schemas are not
 * interchangeable: `dataExtractionRules` wants <data-extraction-rules>,
 * `fullBackupContent` wants <full-backup-content>. minSdk here is 24, so both
 * ship, and each Android version reads the one it understands.
 */
const { withAndroidManifest, withDangerousMod, AndroidConfig } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

/** Android 12+ (API 31+). Also governs device-to-device transfer. */
const MODERN = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by plugins/withBackupRules.js. Do not edit by hand. -->
<data-extraction-rules>
    <cloud-backup>
        <!-- Receipt photos would blow the 25 MB Auto Backup quota and take the
             database down with them. They travel in the backup ZIP instead. -->
        <exclude domain="file" path="receipts" />
        <!-- Local snapshots of the database, inside the cloud copy of that same
             database. Redundant, and expensive against a 25 MB ceiling. -->
        <exclude domain="file" path="backups" />
    </cloud-backup>
    <device-transfer>
        <!-- Phone to phone is a direct cable or local Wi-Fi copy with no 25 MB
             ceiling, so here the photos SHOULD come along. Everything is
             included by default; only the redundant snapshots are dropped. -->
        <exclude domain="file" path="backups" />
    </device-transfer>
</data-extraction-rules>
`;

/** Android 11 and below (API 24-30). Cloud backup only; no transfer concept. */
const LEGACY = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by plugins/withBackupRules.js. Do not edit by hand. -->
<full-backup-content>
    <exclude domain="file" path="receipts" />
    <exclude domain="file" path="backups" />
</full-backup-content>
`;

function withBackupRuleFiles(config) {
  return withDangerousMod(config, [
    'android',
    async (cfg) => {
      const xmlDir = path.join(cfg.modRequest.platformProjectRoot, 'app/src/main/res/xml');
      fs.mkdirSync(xmlDir, { recursive: true });
      fs.writeFileSync(path.join(xmlDir, 'backup_rules.xml'), MODERN, 'utf8');
      fs.writeFileSync(path.join(xmlDir, 'backup_rules_legacy.xml'), LEGACY, 'utf8');
      return cfg;
    },
  ]);
}

function withBackupManifestAttributes(config) {
  return withAndroidManifest(config, (cfg) => {
    const app = AndroidConfig.Manifest.getMainApplicationOrThrow(cfg.modResults);
    app.$['android:dataExtractionRules'] = '@xml/backup_rules';
    app.$['android:fullBackupContent'] = '@xml/backup_rules_legacy';
    return cfg;
  });
}

module.exports = function withBackupRules(config) {
  return withBackupManifestAttributes(withBackupRuleFiles(config));
};
